version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mypassword  
      MYSQL_DATABASE: mydatabase      
      MYSQL_USER: myuser             
      MYSQL_PASSWORD: myuserpassword 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d  
      - ./functions:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: root                  
      PMA_PASSWORD: mypassword       
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:  

